const graphDatas=[
    {
        type:"line",
        data:{
            labels:[23,24,25,26,27,28,29,30],
            datasets:[
              {
              label:"ACOS",
              backgroundColor:"blue",
              borderColor:"blue",
              data:[0,0,1000,5000,50000,100]
              },
              {
                label:"CTR",
                backgroundColor:"red",
                borderColor:"red",
                data:[0,0,10,50,50,100000]
                },
            ]
          },
          graphTitle:"Ads Spend and Revenue",
          subDivs:[
            {
                head:"Ads Spend",
                value:"$1000",
                percent:"9.9%",
                trend:"up"
            },
            {
                head:"Revenue",
                value:"$100",
                percent:"5.9%",
                trend:"down",
                
            },
            {
                head:"CPC",
                value:"$1000",
                percent:"9.9%",
                trend:"down"
            },{
                head:"ACOS",
                value:"$1000",
                percent:"9.9%",
                trend:"up"
            }
          ]
    },
    {
        type:"line",
        data:{
            labels:[23,24,25,26,27,28,29,30],
            datasets:[
              {
              label:"Date Sep 23-24",
              backgroundColor:"blue",
              borderColor:"blue",
              data:[0,0,1000,5000,5,1000]
              },
              {
                label:"CTR",
                backgroundColor:"red",
                borderColor:"red",
                data:[0,0,10,50,50,100000]
                },
            ]
          },
          graphTitle:"Click Through Rate & Clicks",
          subDivs:[
            {
                head:"Impression",
                value:"$10.5M",
                percent:"9.9%",
                trend:"down"
            },
            {
                head:"Clicks",
                value:"10.5K",
                percent:"5.9%",
                trend:"up",
            },
            {
                head:"CTR",
                value:"0.16%",
                percent:"9.9%",
                trend:"down"
            }
          ]
    },
    {
        type:"bar",
        data:{
            labels:[23,24,25,26,27,28,29,30],
            datasets:[
              {
              label:"Date Sep 23-24",
              backgroundColor:"blue",
              borderColor:"blue",
              data:[0,0,1000,5000,5,1000]
              },
              {
                label:"CTR",
                backgroundColor:"red",
                borderColor:"red",
                data:[0,0,10,50,50,100000]
                },
            ]
          },
          graphTitle:"Conversion Rate & Order",
          subDivs:[
            {
                head:"CVR",
                value:"$10.5M",
                percent:"9.9%",
                trend:"down",
            },
            {
                head:"Orders",
                value:"10.5K",
                percent:"5.9%",
                trend:"up"
            },
          ]
    }
]
export default graphDatas